# Generated by Django 4.2.7 on 2024-03-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='qty',
        ),
    ]
